/*=============================================================
  HOL_COCO_CWORK - Setup Script
  Convenience Store Hot Food Sales Data
  
  Run this script from a Snowflake Workspace (notebook SQL cell)
  to create all objects and load CSV data.
  
  All ID fields use Snowflake's UUID_STRING() function.
=============================================================*/

--------------------------------------------------------------
-- 1. Create Warehouse & Compute Pool
--------------------------------------------------------------
CREATE WAREHOUSE IF NOT EXISTS HOL_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE HOL_WH;

CREATE COMPUTE POOL IF NOT EXISTS HOL_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 300;

--------------------------------------------------------------
-- 2. Create Database & Schemas
--------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS HOL_COCO_CWORK;

USE DATABASE HOL_COCO_CWORK;

CREATE SCHEMA IF NOT EXISTS DATA;
CREATE SCHEMA IF NOT EXISTS TOOLS;
CREATE SCHEMA IF NOT EXISTS AGENTS;

--------------------------------------------------------------
-- 3. Create File Formats & Stages
--------------------------------------------------------------
USE SCHEMA DATA;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE HOL_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  FILE_FORMAT = CSV_FORMAT;

USE SCHEMA TOOLS;

CREATE OR REPLACE STAGE SKILLS_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

USE SCHEMA DATA;

--------------------------------------------------------------
-- 4. Create Tables (UUIDs generated by Snowflake)
--------------------------------------------------------------
CREATE OR REPLACE TABLE DIM_STORE (
    STORE_ID       VARCHAR(36)   DEFAULT UUID_STRING() NOT NULL,
    STORE_NAME     VARCHAR(100)  NOT NULL,
    ADDRESS        VARCHAR(200)  NOT NULL,
    CITY           VARCHAR(100)  NOT NULL,
    STATE          VARCHAR(2)    NOT NULL,
    ZIP_CODE       VARCHAR(10)   NOT NULL,
    LATITUDE       FLOAT,
    LONGITUDE      FLOAT,
    OPENED_DATE    DATE,
    CONSTRAINT PK_DIM_STORE PRIMARY KEY (STORE_ID)
);

CREATE OR REPLACE TABLE DIM_ITEM (
    ITEM_ID        VARCHAR(36)   DEFAULT UUID_STRING() NOT NULL,
    ITEM_NAME      VARCHAR(200)  NOT NULL,
    CATEGORY       VARCHAR(100)  NOT NULL,
    UNIT_PRICE     NUMBER(10,2)  NOT NULL,
    COST_PRICE     NUMBER(10,2)  NOT NULL,
    CALORIES       INTEGER,
    IS_SPICY       BOOLEAN,
    CONSTRAINT PK_DIM_ITEM PRIMARY KEY (ITEM_ID)
);

CREATE OR REPLACE TABLE FACT_ITEM_SALES (
    SALE_ID        VARCHAR(36)   DEFAULT UUID_STRING() NOT NULL,
    STORE_ID       VARCHAR(36)   NOT NULL,
    ITEM_ID        VARCHAR(36)   NOT NULL,
    SALE_DATE      DATE          NOT NULL,
    QUANTITY_SOLD  INTEGER       NOT NULL,
    UNIT_PRICE     NUMBER(10,2)  NOT NULL,
    DISCOUNT_PCT   INTEGER       DEFAULT 0,
    TOTAL_SALES    NUMBER(12,2)  NOT NULL,
    CONSTRAINT PK_FACT_SALES PRIMARY KEY (SALE_ID),
    CONSTRAINT FK_STORE FOREIGN KEY (STORE_ID) REFERENCES DIM_STORE(STORE_ID),
    CONSTRAINT FK_ITEM FOREIGN KEY (ITEM_ID) REFERENCES DIM_ITEM(ITEM_ID)
);

--------------------------------------------------------------
-- 5. Upload files to stage
--    Run this in a PYTHON cell (see upload_to_stage.py)
--------------------------------------------------------------

--------------------------------------------------------------
-- 6. Load Dimension Tables
--    ID columns are omitted; UUID_STRING() default fires.
--------------------------------------------------------------
COPY INTO DIM_STORE (STORE_NAME, ADDRESS, CITY, STATE, ZIP_CODE, LATITUDE, LONGITUDE, OPENED_DATE)
FROM (
    SELECT $1, $2, $3, $4, $5, $6, $7, $8
    FROM @HOL_STAGE/dim_store
)
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

COPY INTO DIM_ITEM (ITEM_NAME, CATEGORY, UNIT_PRICE, COST_PRICE, CALORIES, IS_SPICY)
FROM (
    SELECT $1, $2, $3, $4, $5, $6
    FROM @HOL_STAGE/dim_item
)
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

--------------------------------------------------------------
-- 7. Load Fact Table via staging table + JOIN on natural keys
--------------------------------------------------------------
CREATE OR REPLACE TEMPORARY TABLE STG_FACT_ITEM_SALES (
    STORE_NAME     VARCHAR(100),
    ITEM_NAME      VARCHAR(200),
    SALE_DATE      DATE,
    QUANTITY_SOLD  INTEGER,
    UNIT_PRICE     NUMBER(10,2),
    DISCOUNT_PCT   INTEGER,
    TOTAL_SALES    NUMBER(12,2)
);

COPY INTO STG_FACT_ITEM_SALES
FROM @HOL_STAGE/fact_item_sales
FILE_FORMAT = CSV_FORMAT
ON_ERROR = 'CONTINUE';

INSERT INTO FACT_ITEM_SALES (STORE_ID, ITEM_ID, SALE_DATE, QUANTITY_SOLD, UNIT_PRICE, DISCOUNT_PCT, TOTAL_SALES)
SELECT
    s.STORE_ID,
    i.ITEM_ID,
    stg.SALE_DATE,
    stg.QUANTITY_SOLD,
    stg.UNIT_PRICE,
    stg.DISCOUNT_PCT,
    stg.TOTAL_SALES
FROM STG_FACT_ITEM_SALES stg
JOIN DIM_STORE s ON s.STORE_NAME = stg.STORE_NAME
JOIN DIM_ITEM i ON i.ITEM_NAME = stg.ITEM_NAME;

DROP TABLE IF EXISTS STG_FACT_ITEM_SALES;

--------------------------------------------------------------
-- 8. Verify Load
--------------------------------------------------------------
SELECT 'DIM_STORE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_STORE
UNION ALL
SELECT 'DIM_ITEM', COUNT(*) FROM DIM_ITEM
UNION ALL
SELECT 'FACT_ITEM_SALES', COUNT(*) FROM FACT_ITEM_SALES;
